### ISSUE TITLE
"Did not find a best constructor concrete type" error after updating to 2.1

### ISSUE THREAD

**Issue by Piedone** [moq/Moq.AutoMocker#88]
This started happening with 2.1, the same code is fine with 2.0.1.

If a class has a constructor parameter of type `Microsoft.AspNetCore.Http.HttpRequest` or `Microsoft.AspNetCore.Routing.LinkGenerator` (note that both are concrete types) then exceptions of the following kind are thrown:

```
System.ArgumentException : Did not find a best constructor for `Microsoft.AspNetCore.Http.HttpRequest` (Parameter 'type')
at Moq.AutoMock.ConstructorSelector.SelectCtor(Type type, Type[] existingTypes, BindingFlags bindingFlags)
at Moq.AutoMock.AutoMocker.CreateArguments(Type type, ObjectGraphContext context)
at Moq.AutoMock.Resolvers.MockResolver.Resolve(MockResolutionContext context)
at Moq.AutoMock.AutoMocker.Resolve(Type serviceType, Object initialValue, ObjectGraphContext resolutionContext)
at Moq.AutoMock.AutoMocker.Resolve(Type serviceType, ObjectGraphContext resolutionContext)
at Moq.AutoMock.AutoMocker.GetMockImplementation(Type serviceType)
at Moq.AutoMock.AutoMocker.GetMock[TService]()
at MyProject.Tests.UnitTests.Services.MyClassTests.<>c__DisplayClass10_0.<CreateClaimsPrincipal>b__0(AutoMocker mocker) in C:\Agent3\work\FINI\src\Modules\MyProject\Tests\MyProject.Tests\UnitTests\Services\MyClassTests.cs:line 170
at Lombiq.Tests.Helpers.MockHelper.CreateAutoMockerInstance[T](Action`1 configurator, AutoMocker& mocker) in C:\Agent3\work\FINI\test\Lombiq.Tests\Helpers\MockHelper.cs:line 42
at MyProject.Tests.UnitTests.Services.MyClassTests.CreateClaimsPrincipal(User user, UserVerificationSettings settings, IDictionary`2 cookies, UserProfilePart userProfilePart) in C:\Agent3\work\FINI\src\Modules\MyProject\Tests\MyProject.Tests\UnitTests\Services\MyClassTests.cs:line 137
at MyProject.Tests.UnitTests.Services.MyClassTests.DaysSinceLastVerificationClaimShouldBeAccurate() in C:\Agent3\work\FINI\src\Modules\MyProject\Tests\MyProject.Tests\UnitTests\Services\MyClassTests.cs:line 102
```

I'd guess this has to do something with https://github.com/moq/Moq.AutoMocker/pull/86.

**Comment by adamhewitt627** [comment]
This ends up being because we don't include the protected constructor of `HttpRequest` in the default resolution here: https://github.com/moq/Moq.AutoMocker/blob/3c5eea1474767337ae40603529d45f0b27ad43fe/Moq.AutoMock/ConstructorSelector.cs#L11-L18. Specifically, `bindingFlags == Instance | Public`.

I also found that there is still a failure to resolve in 2.0, it is just delayed. For example,
```cs
public class SomeController
{
    public SomeController(HttpRequest request) { }
}


// As noted, this works in 2.0, but throws a stack trace like the above in 2.1
var controllerMock = mocker.GetMock<SomeController>();

// However, this throws in 2.0 resolving Object because it can't find a valid constructor on HttpRequest
Sut(controllerMock.Object);
```

**Comment by Piedone** [comment]
Thank you for your quick reply, Adam!

**Comment by lkurzyniec** [comment]
When we can expect stable version with that fix?

**Comment by adamhewitt627** [comment]
Sorry, I've been in the midst of a job change and didn't mean to drop this. Testing aside, it *could* be as simple as changing the `false` to `true` here. Maybe that's the better default, though in other methods we've exposed that bool up the call stack, such as `CreateInstance(bool enablePrivate)`.

https://github.com/moq/Moq.AutoMocker/blob/004e965d77ad4e1e1a208a9c92412e96e023576e/Moq.AutoMock/AutoMocker.cs#L348-L351

**Comment by Piedone** [comment]
Thank you @adamhewitt627! Does this mean after updating AutoMocker is supposed to work as with 2.0, or is some configuration needed?

**Comment by adamhewitt627** [comment]
The issue is the exclusion of non-public constructors when it attempts to create the dependency. To align with the `CreateInstance` call, you _do_ need to pass a flag:
```cs
IService service = mocker.GetMock<IService>(enablePrivate: true);
```

**Comment by Piedone** [comment]
I see, thank you! Updated and works flawlessly.

**Comment by eddex** [comment]
Just stumbled upon this. I was refactoring some tests to use `AutoMocker.GetMock()` instead of `new Mock()` and my tests started failing with the exception: "System.ArgumentException : Did not find a best constructor for `Microsoft.AspNetCore.Http.HttpRequest` (Parameter 'type')".

```csharp
[Fact] // fails
public void UseAutoMocker()
{
    this.AutoMocker.GetMock<HttpRequest>();
}

[Fact] // works
public void UseMock()
{
    new Mock<HttpRequest>();
}
```

Simply adding the `enhablePrivate: true` parameter in the constructor fixed the problem.

```csharp
[Fact] // works
public void UseAutoMocker()
{
    this.AutoMocker.GetMock<HttpRequest>(true);
}
```

Thanks @adamhewitt627! 🎉
